// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3so63FjlYfmGXEJLQhRPzAzqZDfHrjpo',
    appId: '1:526878722079:web:3f3b9d46e473b6f1242d2a',
    messagingSenderId: '526878722079',
    projectId: 'vehiclerentalapp-fe05a',
    authDomain: 'vehiclerentalapp-fe05a.firebaseapp.com',
    storageBucket: 'vehiclerentalapp-fe05a.appspot.com',
    measurementId: 'G-0CPF0Q6RFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXFMm4cm6ZQCqSvDcbMqTb-AU6pfpxGaQ',
    appId: '1:526878722079:android:fe90c7f6ad0c1b08242d2a',
    messagingSenderId: '526878722079',
    projectId: 'vehiclerentalapp-fe05a',
    storageBucket: 'vehiclerentalapp-fe05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZppvyY8yuNjPabO19em8No-S-NrfQTcw',
    appId: '1:526878722079:ios:f0970cd8b155b78e242d2a',
    messagingSenderId: '526878722079',
    projectId: 'vehiclerentalapp-fe05a',
    storageBucket: 'vehiclerentalapp-fe05a.appspot.com',
    androidClientId: '526878722079-tsl9ga5qfivv468t71gvcrdaoo3vtc1a.apps.googleusercontent.com',
    iosClientId: '526878722079-k5jqkneigpprm5plube2in81mt3kph7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicleRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZppvyY8yuNjPabO19em8No-S-NrfQTcw',
    appId: '1:526878722079:ios:f0970cd8b155b78e242d2a',
    messagingSenderId: '526878722079',
    projectId: 'vehiclerentalapp-fe05a',
    storageBucket: 'vehiclerentalapp-fe05a.appspot.com',
    androidClientId: '526878722079-tsl9ga5qfivv468t71gvcrdaoo3vtc1a.apps.googleusercontent.com',
    iosClientId: '526878722079-k5jqkneigpprm5plube2in81mt3kph7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicleRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3so63FjlYfmGXEJLQhRPzAzqZDfHrjpo',
    appId: '1:526878722079:web:02162d8a1ef31c5a242d2a',
    messagingSenderId: '526878722079',
    projectId: 'vehiclerentalapp-fe05a',
    authDomain: 'vehiclerentalapp-fe05a.firebaseapp.com',
    storageBucket: 'vehiclerentalapp-fe05a.appspot.com',
    measurementId: 'G-ZPRF1SWQV9',
  );

}